name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    env:
      working-directory: .
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        working-directory: ${{env.working-directory}}
        run: npm ci

      - name: Lint
        working-directory: ${{env.working-directory}}
        run: npm run lint

      - name: Build
        working-directory: ${{env.working-directory}}
        run: npm run build
